# Generated by Django 2.1.5 on 2019-03-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('list_date', models.DateField(auto_now_add=True)),
                ('lot_size', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('is_commercial', models.BooleanField()),
                ('business', models.CharField(max_length=20)),
                ('num_of_buildings', models.PositiveIntegerField()),
                ('is_residential', models.BooleanField()),
                ('residence_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_user_id', to='global_listing.User'),
        ),
    ]
