# Generated by Django 2.1.5 on 2019-03-16 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import global_listing.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('list_date', models.DateField(auto_now_add=True)),
                ('above_grade_sqft', models.PositiveIntegerField(null=True)),
                ('lot_size', models.PositiveIntegerField(null=True)),
                ('post_title', models.CharField(max_length=128, null=True)),
                ('post_priority', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=2450)),
                ('is_commercial', models.BooleanField(null=True)),
                ('business', models.CharField(max_length=30, null=True)),
                ('num_of_buildings', models.PositiveIntegerField(null=True)),
                ('is_residential', models.BooleanField(null=True)),
                ('residence_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=25)),
                ('postal', models.CharField(max_length=7)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_address', to='global_listing.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to=global_listing.models.get_image_filename, verbose_name='Image')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_image', to='global_listing.Property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomFlooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooring', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('ceiling_heights', models.FloatField()),
                ('is_insulated', models.BooleanField()),
                ('num_of_windows', models.PositiveIntegerField()),
                ('fireplace', models.BooleanField()),
                ('size', models.FloatField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_space', to='global_listing.Property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=30)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_room_type', to='global_listing.RoomSpace')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_room_type', to='global_listing.RoomSpace')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('phone_day', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roomflooring',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_room_flooring', to='global_listing.RoomSpace'),
        ),
        migrations.AddField(
            model_name='roomflooring',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_room_flooring', to='global_listing.RoomSpace'),
        ),
        migrations.AddField(
            model_name='roomdimension',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_room_dimension', to='global_listing.RoomSpace'),
        ),
        migrations.AddField(
            model_name='roomdimension',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_room_dimension_rm', to='global_listing.RoomSpace'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_user', to='global_listing.UserProfile'),
        ),
    ]
