# Generated by Django 2.1.5 on 2019-03-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaddress',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_address', to='global_listing.Property'),
        ),
    ]
