# Generated by Django 2.1.5 on 2019-03-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('ceiling_heights', models.FloatField()),
                ('is_insulated', models.BooleanField()),
                ('num_of_windows', models.PositiveIntegerField()),
                ('fireplace', models.BooleanField()),
                ('size', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='business',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='residence_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='roomspace',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_property_id', to='global_listing.Property'),
        ),
    ]
