# Generated by Django 2.1.5 on 2019-03-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0002_auto_20190307_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='roomspace',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomspace_property_id', to='global_listing.Property'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomtype_property_id', to='global_listing.RoomSpace'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomtype_room_id', to='global_listing.RoomSpace'),
        ),
    ]
