# Generated by Django 2.1.5 on 2019-03-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0003_auto_20190307_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.FloatField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomdimension_property_id', to='global_listing.RoomSpace')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomdimension_room_id', to='global_listing.RoomSpace')),
            ],
        ),
    ]
