# Generated by Django 2.1.5 on 2019-03-07 02:58

from django.db import migrations, models
import django.db.models.deletion
import global_listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0004_roomdimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=25)),
                ('postal', models.CharField(max_length=7)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propertyaddress_property_id', to='global_listing.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=global_listing.models.get_image_filename, verbose_name='Image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propertyimages_property_id', to='global_listing.Property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFlooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooring', models.CharField(max_length=30)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomfloor_property_id', to='global_listing.RoomSpace')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roomfloor_room_id', to='global_listing.RoomSpace')),
            ],
        ),
    ]
