# Generated by Django 2.1.5 on 2019-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0006_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.AddField(
            model_name='property',
            name='post_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
