# Generated by Django 2.1.5 on 2019-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0007_auto_20190310_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='post_priority',
            field=models.IntegerField(default=1),
        ),
    ]
