# Generated by Django 2.1.5 on 2019-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0008_property_post_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='above_grade_sqft',
            field=models.PositiveIntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='num_of_buildings',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
