# Generated by Django 2.1.5 on 2019-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0009_auto_20190310_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='image_title',
            field=models.CharField(default='image', max_length=50),
            preserve_default=False,
        ),
    ]
