# Generated by Django 2.1.5 on 2019-03-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0010_propertyimages_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='image_title',
            new_name='name',
        ),
    ]
