# Generated by Django 2.1.5 on 2019-03-11 01:57

from django.db import migrations, models
import django.db.models.deletion
import global_listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0012_auto_20190311_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=global_listing.models.get_image_filename, verbose_name='Image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propertyimages_property_id', to='global_listing.Property')),
            ],
        ),
    ]
