# Generated by Django 2.1.5 on 2019-03-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0013_propertyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='name',
        ),
        migrations.AlterField(
            model_name='property',
            name='above_grade_sqft',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='business',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=2450),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_commercial',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_residential',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='post_title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='residence_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='propertyimages_property_id', to='global_listing.Property'),
        ),
    ]
