# Generated by Django 2.1.5 on 2019-03-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0014_auto_20190311_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='property_id',
        ),
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
