# Generated by Django 2.1.5 on 2019-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0016_propertyimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='test_upload', verbose_name='Image'),
        ),
    ]
