# Generated by Django 2.1.5 on 2019-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0017_auto_20190313_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='img_upload/%Y/%m/%D/', verbose_name='Image'),
        ),
    ]
