# Generated by Django 2.1.5 on 2019-03-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_listing', '0018_auto_20190313_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='property_id',
        ),
    ]
